### ISSUE TITLE
Include repository name in PR modal

### ISSUE THREAD

**Issue by adammorr** [martincostello/dependabot-helper#495]
### Is your feature request related to a problem? Please describe.

It would be helpful to include the repository name in the PR modal so you can keep track of what you're managing, especially when you have a number of repositories.

### Describe the solution you'd like

Including the repository name in the modal, perhaps in the title or footer;

![image](https://user-images.githubusercontent.com/7453217/224646253-92ee9ac2-0d7b-47b6-ad49-e9d62117ef78.png)

### Describe alternatives you've considered

Trying to remember which repository I am managing 😄 

### Additional context

n/a

**Comment by adammorr** [comment]
Also happy to raise a PR for this if it makes sense and I've not missed anything obvious

**Comment by martincostello** [comment]
Happy to accept a PR for this if you’re up for it - will be a test of how approachable my own code actually is for others 😅

The feature makes sense as a little add-on for some extra context. I think it’ll almost be exclusively be changes to the TypeScript and Razor page.

**Comment by adammorr** [comment]
Yeah sure, I'll attempt to raise something this week 👍

**Comment by martincostello** [comment]
I had to touch the same area of code resolving #503, so I've included a change for this in the same PR.
