### ISSUE TITLE
Indication of PR approval is lost when closing / re-opening PR list

### ISSUE THREAD

**Issue by adammorr** [martincostello/dependabot-helper#503]
**Describe the bug**

If I approve a PR then close and re-open the same PR list, it no longer shows that I have approved it (the icon is missing).

**Steps To reproduce**

1. Open PR list for a repository
2. Approve a PR (wait for the icon to indicate it has completed)
3. Close PR modal
4. Re-open the same PR modal
5. Icon against the PR you have approved is no longer shown

**Expected behaviour**

I would expect to see an indication that the PR has already been approved by me rather than nothing

**Actual behaviour**

No indication of the PR being approved is shown

**Screenshots**

_Initial approval (tick shown)_

![image](https://user-images.githubusercontent.com/7453217/224921297-aef01585-eb5e-4769-8b4b-acf28c4a859a.png)

_Re-open (tick not shown)_

![image](https://user-images.githubusercontent.com/7453217/224921348-56a81165-9a4b-4ef6-9bae-3b378a767ce8.png)

**System information:**

Chrome Version 111.0.5563.65 (Official Build) (64-bit)

**Additional context**

HTML for cell is;

```html
<td class="text-center mt-3 mt-lg-1">
    <span>
        <span class="fa-solid fa-xmark text-danger pr-status-error d-none" data-count="0" aria-label="Error" title="Error"></span>
        <span class="fa-solid fa-spinner text-warning pr-status-pending d-none" data-count="0" aria-label="Pending" title="Pending"></span>
        <span class="fa-solid fa-check text-success pr-status-success d-none" data-count="0" aria-label="Success" title="Success"></span>
    </span>
    <span>
        <span class="fa-solid fa-thumbs-up text-primary pr-is-approved d-none" data-count="0" aria-label="Approved" title="Approved"></span>
        <button class="btn btn-success btn-approve pr-approve d-none" type="button" aria-label="Approve this pull request" analytics-event="approve_pull_request">
            <span>Approve</span>
            <span class="fa-solid fa-check d-none d-md-inline-block" aria-hidden="true"></span>
            <span class="loader spinner-border spinner-border-sm d-none" role="status">
                <span class="sr-only">Approving...</span>
            </span>
        </button>
    </span>
</td>
```

**Comment by martincostello** [comment]
How many reviews are required on a pull request in the repo you're seeing this with?

If it's more than 1, then that would explain this behaviour as it wouldn't be _"approved enough"_, but the button won't be displayed because _you_ approved it.

The logic for handling the reviews is here:

https://github.com/martincostello/dependabot-helper/blob/266011ce4cce54b6ab7bed3919c3f27ab77638d9/src/DependabotHelper/GitHubService.cs#L443-L493

If that isn't what it is, then as I've not seen this before, then it's probably a quirk of your user and the repo in question, so you might need to debug it yourself locally to work out what's going on.

**Comment by adammorr** [comment]
The repo requires 2 so that would explain it 👍 is there any reason we couldn't show something to indicate you have already reviewed it?

**Comment by martincostello** [comment]
Sure - I'll look at having something, rather than just a blank space.
